const SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTkHOkygOrrQTtoGTP5ivH6Fe-U_Ym1cqrt7TymLNEHyTSOE1KQJOnCLqi0KpuUEA_UVkXvL8a5OQoe/pub?gid=0&single=true&output=csv';

const FLAGS = {
  'canada':         'ca', 'mexico':         'mx', 'usa':            'us',
  'algeria':        'dz', 'argentina':      'ar', 'australia':      'au',
  'austria':        'at', 'belgium':        'be', 'brazil':         'br',
  'cabo verde':     'cv', 'colombia':       'co', 'croatia':        'hr',
  'curaçao':        'cw', 'côte d\'ivoire': 'ci', 'ecuador':        'ec',
  'egypt':          'eg', 'england':        'gb-eng', 'france':      'fr',
  'germany':        'de', 'ghana':          'gh', 'haiti':          'ht',
  'ir iran':        'ir', 'japan':          'jp', 'jordan':         'jo',
  'korea republic': 'kr', 'morocco':        'ma', 'netherlands':    'nl',
  'new zealand':    'nz', 'norway':         'no', 'panama':         'pa',
  'paraguay':       'py', 'portugal':       'pt', 'qatar':          'qa',
  'saudi arabia':   'sa', 'scotland':       'gb-sct', 'senegal':    'sn',
  'south africa':   'za', 'spain':          'es', 'switzerland':    'ch',
  'tunisia':        'tn', 'uruguay':        'uy', 'uzbekistan':     'uz',
  'ireland':        'ie', 'all nations':    null,
};

const MAP_STYLE = [
  { elementType: 'geometry',        stylers: [{ color: '#111111' }] },
  { elementType: 'labels.text.fill',stylers: [{ color: '#888888' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#111111' }] },
  { featureType: 'road',            elementType: 'geometry',       stylers: [{ color: '#1e1e1e' }] },
  { featureType: 'road',            elementType: 'geometry.stroke', stylers: [{ color: '#2a2a2a' }] },
  { featureType: 'road',            elementType: 'labels.text.fill', stylers: [{ color: '#666666' }] },
  { featureType: 'road.highway',    elementType: 'geometry',       stylers: [{ color: '#2a2a2a' }] },
  { featureType: 'road.highway',    elementType: 'geometry.stroke', stylers: [{ color: '#333333' }] },
  { featureType: 'water',           elementType: 'geometry',       stylers: [{ color: '#0a0a0a' }] },
  { featureType: 'water',           elementType: 'labels.text.fill', stylers: [{ color: '#444444' }] },
  { featureType: 'poi',             elementType: 'geometry',       stylers: [{ color: '#151515' }] },
  { featureType: 'poi',             elementType: 'labels.text.fill', stylers: [{ color: '#555555' }] },
  { featureType: 'poi.park',        elementType: 'geometry',       stylers: [{ color: '#131a14' }] },
  { featureType: 'transit',         elementType: 'geometry',       stylers: [{ color: '#181818' }] },
  { featureType: 'administrative',  elementType: 'geometry.stroke', stylers: [{ color: '#2a2a2a' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#aaaaaa' }] },
  { featureType: 'landscape',       elementType: 'geometry',       stylers: [{ color: '#111111' }] },
  { featureType: 'poi', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.business', stylers: [{ visibility: 'off' }] },
  { featureType: 'transit', elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
];